# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  verify:
    
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install CycloneDX in dotnet cli
      run: dotnet tool install --global CycloneDX
    
    - name: CycloneDX .NET Generate SBOM
      run: dotnet CycloneDX ChainGuardian.DotNetNuGet.sln -j -o . 
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
          path: | 
              ChainGuardian.DotNetNuGet.1.0.0.nupkg
              bom.json
          name: DocGenerator
          if-no-files-found: error
          retention-days: 5
